import { Archetype } from "@/types/perazzi-assistant";

export interface ArchetypeLexiconEntry {
  high: readonly string[]; // strongest signals
  mid: readonly string[];  // moderate signals
  low: readonly string[];  // weak / contextual signals
  negatives?: readonly string[]; // cancel boost if present
}

export type ArchetypeKeywordLexicon = Record<Archetype, ArchetypeLexiconEntry>;

// Expanded Pass-3+ lexicon with tiered weights, variants, and bigrams
export const DEFAULT_LEXICON: ArchetypeKeywordLexicon = {
  loyalist: {
    high: [
      "i've always",
      "i have always",
      "had this gun",
      "my perazzi for",
      "for years",
      "for decades",
      "love this gun",
      "favorite gun",
      "my dad's perazzi",
      "my fathers perazzi",
      "perazzi guy",
      "wouldn't shoot anything else",
      "club night",
      "squad",
      "teammates",
      "lifelong",
      "together",
      "our gun",
      "trust",
      "dependable",
      "never let me down",
    ],
    mid: [
      "club night",
      "squad",
      "teammates",
      "range buddy",
      "lifelong",
      "together",
      "our gun",
      "good old perazzi",
    ],
    low: [
      "trust",
      "dependable",
      "never let me down",
    ],
    negatives: ["loyalty program"],
  },
  prestige: {
    high: [
      "beautiful",
      "engraving",
      "engravings",
      "deep scroll",
      "gold inlay",
      "wood",
      "exhibition wood",
      "presentation grade",
      "stock figure",
      "aesthetic",
      "aesthetics",
      "finish",
      "luxury",
      "luxurious",
      "limited run",
      "collector's edition",
      "statement piece",
      "conversation starter",
      "stand-out",
      "exclusive",
      "bespoke",
      "bespoke engraving",
      "artisanal",
      "craftsmanship",
      "upgrade",
      "presentation",
    ],
    mid: [
      "italian scrollwork",
      "mirror bluing",
      "hand-cut checkering",
      "diamond-grade",
      "presentation case",
    ],
    low: [
      "exclusive",
      "stand-out",
      "statement piece",
    ],
    negatives: ["luxury tax"],
  },
  analyst: {
    high: [
      "point of impact",
      "impact point",
      "shot impact",
      "poi",
      "trigger weight",
      "rib height",
      "barrel convergence",
      "pattern",
      "patterning",
      "grouping",
      "standard deviation",
      "choke",
      "chokes",
      "fps",
      "muzzle velocity",
      "ft-lb",
      "trajectory",
      "length of pull",
      "lop",
      "drop at comb",
      "drop at heel",
      "cast",
      "toe",
      "pitch",
      "balance",
      "weight distribution",
      "chronograph",
      "calipers",
      "high-speed video",
      "force plate",
      "protocol",
      "repeatability",
      "control group",
      "variable",
      "coefficient",
      "spec",
      "specs",
      "compare",
      "comparison",
    ],
    mid: [
      "90/10 pattern",
      "shot velocity spread",
      "harmonic node balance",
      "ballistic coefficient",
    ],
    low: [
      "variable",
      "control group",
      "repeatability",
      "calipers",
    ],
    negatives: ["social impact", "impact report"],
  },
  achiever: {
    high: [
      "score",
      "scores",
      "results",
      "scoresheet",
      "leaderboard",
      "winning",
      "nationals",
      "world championship",
      "competition",
      "high score",
      "performance",
      "consistency",
      "more consistent",
      "tournament",
      "major event",
      "drills",
      "practice plan",
      "coach",
      "kpi",
      "hit percentage",
      "target count",
      "average",
      "pr score",
      "focus",
      "visualisation",
      "peak state",
      "pressure",
      "routine",
    ],
    mid: [
      "dry-fire routine",
      "pre-shot routine",
      "podium finish",
      "personal record",
    ],
    low: [
      "average",
      "target count",
      "hit percentage",
    ],
  },
  legacy: {
    high: [
      "heirloom",
      "family heirloom",
      "pass it down",
      "passing it down",
      "my kids",
      "my children",
      "next generation",
      "grandfather",
      "generations",
      "provenance",
      "handed-down",
      "original bluing",
      "patina",
      "custodianship",
      "restorative",
      "auction",
      "appraisal",
      "investment",
      "future collector",
      "keep it original",
      "preserve",
      "preserving",
      "history of this gun",
      "family gun",
    ],
    mid: [
      "serial number in the",
      "original receipt",
      "kept original case",
      "auction value",
    ],
    low: [
      "patina",
      "restorative",
      "investment",
    ],
  },
};

export function getArchetypeLexicon(): ArchetypeKeywordLexicon {
  // In future passes we may load variant lexicons; for now, return default.
  return DEFAULT_LEXICON;
}
